# Generated by Django 4.1.7 on 2023-03-11 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ids', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acltypes',
            name='acl',
        ),
        migrations.RemoveField(
            model_name='acltypes',
            name='type',
        ),
        migrations.DeleteModel(
            name='ACL',
        ),
        migrations.DeleteModel(
            name='ACLTypes',
        ),
    ]
