# Generated by Django 4.1.7 on 2023-03-15 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ids', '0004_alter_acltyp_options_alter_position_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='identifikation',
            name='aaa',
            field=models.BooleanField(default=False, help_text='ID matched positiv bei allen Rechten!', verbose_name='Access All Areas'),
        ),
    ]
