# Generated by Django 4.1.7 on 2023-03-15 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ids', '0005_identifikation_aaa'),
    ]

    operations = [
        migrations.AddField(
            model_name='identifikation',
            name='plus',
            field=models.IntegerField(choices=[(0, 'Keine Erlaubnis'), (1, 'Eine Extra Person'), (3, 'Drei Extra Personen'), (99, 'Unendlich!!')], default=0),
        ),
    ]
