# Generated by Django 4.1.7 on 2023-03-15 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ids', '0006_identifikation_plus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='identifikation',
            name='plus',
        ),
        migrations.AddField(
            model_name='acl',
            name='plus',
            field=models.IntegerField(choices=[(0, 'Keine Erlaubnis'), (1, 'Eine Extra Person'), (3, 'Drei Extra Personen'), (99, 'Unendlich!!')], default=0, help_text='Angeben ob der Halter dieser Karte weitere Personen mitnehmen kann', verbose_name='Personen mitnehmen'),
        ),
    ]
