# Generated by Django 4.1.7 on 2023-03-15 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ids', '0007_remove_identifikation_plus_acl_plus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acl',
            name='type',
            field=models.ManyToManyField(blank=True, to='ids.acltyp', verbose_name='Typ'),
        ),
    ]
