# Generated by Django 4.1.7 on 2023-03-16 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ids', '0008_alter_acl_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acl',
            name='plus',
            field=models.IntegerField(choices=[(0, 'Keine Extra Personen!'), (1, 'Eine Extra Person'), (3, 'Drei Extra Personen'), (99, 'Unendlich!')], default=0, help_text='Angeben ob der Halter dieser Karte weitere Personen mitnehmen kann', verbose_name='Personen mitnehmen'),
        ),
        migrations.CreateModel(
            name='IDLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('identifikation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ids.identifikation', verbose_name='ID Karte')),
                ('matched_acl', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ids.acl', verbose_name='Matched ACL')),
                ('matched_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ids.acltyp', verbose_name='Matched Typ')),
            ],
        ),
    ]
