# Generated by Django 4.1.7 on 2023-03-16 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ids', '0009_alter_acl_plus_idlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idlog',
            name='identifikation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='idlogs', to='ids.identifikation', verbose_name='ID Karte'),
        ),
    ]
