# Generated by Django 4.1.7 on 2023-03-17 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ids', '0010_alter_idlog_identifikation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='idlog',
            options={'verbose_name': 'ID Log', 'verbose_name_plural': 'ID Logs'},
        ),
        migrations.AddField(
            model_name='idlog',
            name='match_failed',
            field=models.BooleanField(default=False),
        ),
    ]
