# Generated by Django 4.1.7 on 2023-03-17 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ids', '0011_alter_idlog_options_idlog_match_failed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='idlog',
            old_name='match_failed',
            new_name='match_success',
        ),
    ]
