# Generated by Django 4.1.7 on 2023-03-18 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ids', '0012_rename_match_failed_idlog_match_success'),
    ]

    operations = [
        migrations.AddField(
            model_name='identifikation',
            name='active',
            field=models.BooleanField(default=True, help_text='ID Karten die verloren gehen hier deaktivieren', verbose_name='Aktiv'),
        ),
    ]
