# Generated by Django 4.1.7 on 2023-05-25 10:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ids', '0013_identifikation_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acl',
            options={'verbose_name': 'Berechtigung', 'verbose_name_plural': 'Berechtigungen'},
        ),
        migrations.AlterModelOptions(
            name='acltyp',
            options={'ordering': ['name'], 'verbose_name': 'Rechte-Typ', 'verbose_name_plural': 'Rechte-Typen'},
        ),
        migrations.RemoveField(
            model_name='identifikation',
            name='bild',
        ),
        migrations.RemoveField(
            model_name='identifikation',
            name='position',
        ),
        migrations.AlterField(
            model_name='acl',
            name='type',
            field=models.ManyToManyField(blank=True, to='ids.acltyp', verbose_name='Rechte-Typ'),
        ),
        migrations.AlterField(
            model_name='identifikation',
            name='aaa',
            field=models.BooleanField(default=False, help_text='ID matched positiv bei allen Rechte-Typen!', verbose_name='Access All Areas'),
        ),
        migrations.AlterField(
            model_name='idlog',
            name='matched_acl',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ids.acl', verbose_name='Berechtigung'),
        ),
        migrations.AlterField(
            model_name='idlog',
            name='matched_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ids.acltyp', verbose_name='Rechte-Typ'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bild', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=False, null=True, quality=-1, scale=None, size=[300, 400], upload_to='photos/', verbose_name='ID-Bild')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ids.position', verbose_name='Position')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
